### ISSUE TITLE
NameError: name 'wrap_train' is not defined : somoclu Version: 1.7.5 in windows

### ISSUE THREAD

**Issue by apremgeorge** [peterwittek/somoclu#144]
Hi,
I am getting the error,
```
som_clu.train()
Traceback (most recent call last):

  File "<ipython-input-196-fe94f553b2c4>", line 1, in <module>
    som_clu.train()

  File "C:\ProgramData\Anaconda3\lib\site-packages\somoclu\train.py", line 222, in train
    wrap_train(np.ravel(self._data), epochs, self._n_columns, self._n_rows,

NameError: name 'wrap_train' is not defined
```
```
import somoclu
Warning: the binary library cannot be imported. You cannot train maps, but you can load and analyze ones that you have already saved.
If you installed Somoclu with pip on Windows, this typically means missing DLLs. Please refer to the documentation.
```
I have seen the different issues for the same in discussions, may i know the correct solutions please? Thanks

**Comment by xgdgsc** [comment]
Have you tried some solutions from https://github.com/peterwittek/somoclu/issues/28 ?

**Comment by apremgeorge** [comment]
so I can't see _somoclu_wrap.pyd in site-packages
also vcomp90.dll, msvcp90.dll, msvcr90.dll to be copied to C:\Windows\SysWOW64, i downloaded that from the dll sites, not sure about which versions

**Comment by apremgeorge** [comment]
Hi, May I know any suggestions available please?

**Comment by sahautal** [comment]
I'm having the same issue with Python version 3.7.4 and Somoclu version 1.7.5 . Somoclu 1.7.5 works fine with python 3.6, but with python 3.7.4 I get the same errors as you. However Somoclu version 1.7.4 works fine on python 3.7.4

**Comment by apremgeorge** [comment]
Thanks @sahautal, I have Python 3.7.0, somoclu 1.7.4 worked.

**Comment by mtcarvalho** [comment]
Python 3.7.4 or 3.7.0 with Somoclu 1.7.4 didnt work for me, neither Python 3.6 with Somoclu 1.7.5 :(

**Comment by Guilherme-B** [comment]
I'm having the exact same problem. Tried manually setting the ddls, nothing. I tried downgrading versions and still. with 3.7+ nothing works. Same behavior on 3.8.2.

**Comment by xgdgsc** [comment]
I uploaded https://files.pythonhosted.org/packages/bf/1d/8f2a89cd9a0f37fe3a8ba114f43e310a832f5f30f7f3d886e6379ab2e722/somoclu-1.7.5.1.tar.gz . You can try run `python setup.py install` after extracting. Before that you can install visual studio with visual c++ compilers. From my testing it works.

**Comment by pedromaiapatinha** [comment]
Hey,
I'm having the same problem here, `NameError: name 'wrap_train' is not defined`.
- I'm using the somoclu version 1.7.5.1 (already tried 1.7.4 and 1.7.5);
- Already ran `python setup.py install` successfuly;
- Already installed `libiomp5md`, `msvcp90`, `msvcr90` and `vcomp90`;
- Also, I have visual studio with visual c++ compilers.

Any ideia? Thank you

**Comment by xgdgsc** [comment]
Which version of VS? I only tested latest .

**Comment by guba-odudkin** [comment]
@xgdgsc @pedromaiapatinha Any update on this? Still an issue for me. Everything is latest. I only got as far as figuring out that setup.py fails to compile with error code 2. But it doesn't fail the process, so unless you scroll up you won't know it failed, it reports that install was successful. As the result _somoclu_wrap.pyd isn't getting created and I get the above error. 
Thanks in advance for any tips towards a solution.

**Comment by rodiegeology** [comment]
It worked for me using this solution for installing the 1.7.5.1 version, the error does not appear anymore. However my Jupyter Notebook kernel dies everytime I try to train data, even small datasets. Windows 10 64 bits, Anaconda 3, Python 3.8. 

> @xgdgsc @pedromaiapatinha Any update on this? Still an issue for me. Everything is latest. I only got as far as figuring out that setup.py fails to compile with error code 2. But it doesn't fail the process, so unless you scroll up you won't know it failed, it reports that install was successful. As the result _somoclu_wrap.pyd isn't getting created and I get the above error.
> Thanks in advance for any tips towards a solution.

**Comment by helt** [comment]
I run ito the same issue as @rodiegeology . I also tried to run it in python directly, but the result remains the same: The python interpreter dies.

Do I understand correctly that - to get somoclu up and running on windows - I have to have Visual Studio? Visual Studio Build Tools are not sufficient for this task?

**Comment by yangdeai** [comment]
it works on Ubuntu20.04(conda install somoclu  -c conda-forge), but fails on windows10(conda install somoclu -c conda-forge), anyone help?

**Comment by maxwest-uw** [comment]
Hi, I'm having this same error with somoclu but with a Macbook M1 pro, I see that the 1.7.5.1 change above is pushed to pypi but it fails to actually build locally:
```
```

**Comment by xgdgsc** [comment]
Uploaded src package 1.7.6 to pypi.

**Comment by xgdgsc** [comment]
Conda updated with M1 build, please test if you have a M1 device.

**Comment by AkinaMH** [comment]
Hello, I'm using Python 3.9.12 and Somoclu 1.7.5 on Windows and I still get the error NameError: name 'wrap_train' is not defined

**Comment by vkresch** [comment]
Any updates on this issue? Have the same issue in Ubuntu 20.04. How can I resolve this? I am using somoclu==1.7.6 in an virtual environment. cc @peterwittek

**Comment by vkresch** [comment]
Solved with:
`pip install -U numpy`
