### ISSUE TITLE
train throws Exception: No data was provided!

### ISSUE THREAD

**Issue by passionato** [peterwittek/somoclu#74]
I am running the classic example provided on the website:

```
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import somoclu
c1 = np.random.rand(50, 3)/5
c2 = (0.6, 0.1, 0.05) + np.random.rand(50, 3)/5
c3 = (0.4, 0.1, 0.7) + np.random.rand(50, 3)/5
data = np.float32(np.concatenate((c1, c2, c3)))
colors = ["red"] * 50
colors.extend(["green"] * 50)
colors.extend(["blue"] * 50)
fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(data[:, 0], data[:, 1], data[:, 2], c=colors)
labels = range(150)
plt.show()
n_rows, n_columns = 100, 160
som = somoclu.Somoclu(n_columns, n_rows, compactsupport=False)
som.train(data)
```

and unfortunately I am getting this error:

```
Traceback (most recent call last):
  File "Test.py", line 19, in <module>
    som.train(data)
  File "/usr/local/lib/python2.7/dist-packages/somoclu/train.py", line 197, in train
    raise Exception("No data was provided!")
Exception: No data was provided!
```

what am I missing here? what is wrong? could somebody help me understand this?

I am on ubuntu and here is the log for installing somoclu:
https://pastebin.com/Keeh6XS6

**Comment by xgdgsc** [comment]
I' ve tried this on ubuntu 16.04 python2 (anaconda) . It works for me. I installed the package using `pip install somoclu`. Have you tried using pip to install?
